"""CALL-E voice-call integration.

Responsible for scheduling a single outbound feedback call per order and
extracting the transcript. Raw audio is never stored. If CALL-E is not
configured the call is recorded as `simulated` (never presented as real).
"""

from __future__ import annotations

from typing import Any

from .config import Settings
from .llm import complete_json, get_llm

# Customer-facing call-script text is generated by the LLM, in the customer's
# actual (detected) language, rather than a hardcoded per-language template —
# this is a deliberate design choice (see project notes on preferred_language).
# The one exception is the single, language-neutral sentence in
# `_FALLBACK_TASK` below, used ONLY when no LLM provider is configured/
# available at all, so call dispatch never breaks outright.
_SCRIPT_SYSTEM = (
    "You write a short call-task instruction for an AI voice agent that is "
    "about to call a customer on behalf of a business, to collect feedback "
    "about a recently completed order or service. Write the ENTIRE "
    "instruction in the requested language — never mix languages. The "
    "instruction must tell the agent to: (1) open with a short, fixed "
    "greeting identifying the business and the reason for the call; "
    "(2) then let the customer speak freely; (3) listen for satisfaction, "
    "issues and suggestions without asking unnecessary questions; (4) be "
    "brief and natural. If a comma-separated list of previously reported "
    "issues is given as additional context, add ONE natural follow-up "
    "question asking whether that specific issue happened again this time — "
    "use only the given issue names verbatim, never invent details or repeat "
    "any other customer data. Return JSON only, no markdown: "
    '{"task": "<the full instruction text, entirely in the requested language>"}'
)

_FALLBACK_TASK = (
    "On behalf of {business}, call the customer to collect feedback about "
    "their completed order. Use a short fixed opening, then let the customer "
    "speak freely about satisfaction, issues or suggestions."
)


def _generate_task_text(
    llm: Any, business_name: str, language: str, context: str | None
) -> str | None:
    """Ask the configured LLM to write the call-task instruction in
    `language`. Returns None on any failure (network, malformed JSON, no
    provider) so the caller can fall back to `_FALLBACK_TASK`."""
    if llm is None:
        return None
    user = f"Business name: {business_name}\nLanguage: {language}\n"
    if context:
        user += f"Previously reported issues (use verbatim, do not translate names): {context}\n"
    result = complete_json(llm, _SCRIPT_SYSTEM, user)
    if result and result.get("task"):
        text = str(result["task"]).strip()
        return text or None
    return None


# -- GÖREV 2: re-engagement outreach (dormant customer with a past verified
# complaint). No hardcoded fallback template here on purpose: if no LLM is
# available, the caller (Pipeline.propose_reengagement_outreach) simply skips
# proposing anything rather than showing a generic, non-personalized message.
_REENGAGEMENT_SYSTEM = (
    "You write a short, warm call-task instruction for an AI voice agent "
    "calling a customer who has not ordered in a while, to check in. Write "
    "the ENTIRE instruction in the requested language. Tell the agent to: "
    "(1) greet warmly and mention the business missed them; (2) reference "
    "the previously reported issue(s) given as context and ask, naturally, "
    "whether it has been resolved since; (3) invite them back without being "
    "pushy or salesy; (4) be brief and natural. Use only the given issue "
    "names verbatim, never invent details. Return JSON only, no markdown: "
    '{"task": "<the full instruction text, entirely in the requested language>"}'
)

# -- GÖREV 3: approved compensation-offer notification call. A single,
# language-neutral fallback exists here too (calling to inform of an already
# human-approved offer is an operational necessity, not optional content).
_OFFER_SYSTEM = (
    "You write a short call-task instruction for an AI voice agent calling a "
    "customer to inform them that a compensation offer was approved for a "
    "past issue with their order. Write the ENTIRE instruction in the "
    "requested language. Tell the agent to: (1) greet the customer briefly, "
    "naming the business; (2) clearly state that a {percentage}% discount/"
    "compensation was approved for their recent order; (3) give a clear, "
    "unambiguous call-to-action: they must contact the business within 48 "
    "hours to claim it, otherwise it will not be applied automatically; "
    "(4) be brief, warm and factual — this is a notification, not a sales "
    "pitch. Return JSON only, no markdown: "
    '{{"task": "<the full instruction text, entirely in the requested language>"}}'
)

_OFFER_FALLBACK_TASK = (
    "On behalf of {business}, tell the customer that a {percentage}% "
    "compensation offer was approved for their recent order. They must "
    "contact the business within 48 hours to claim it, otherwise it will not "
    "be applied automatically. Be brief, warm and clear."
)


RESULT_SCHEMA = {
    "type": "object",
    "properties": {
        "satisfaction_score": {"type": "integer", "description": "1 to 5"},
        "sentiment": {
            "type": "string",
            "enum": ["positive", "neutral", "negative"],
        },
        "missing_items": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Items the customer said were missing from the order.",
        },
        "customer_summary": {
            "type": "string",
            "description": "Short summary of what the customer said.",
        },
    },
    "required": ["sentiment", "customer_summary"],
    "additionalProperties": False,
}


_BCP47 = {"tr": "tr-TR", "en": "en-US", "de": "de-DE"}

_REGION_BY_PREFIX = {
    "+90": "TR",
    "+1": "US",
    "+49": "DE",
    "+44": "GB",
    "+31": "NL",
    "+33": "FR",
    "+34": "ES",
    "+39": "IT",
}


def region_from_phone(phone: str) -> str | None:
    for prefix, region in _REGION_BY_PREFIX.items():
        if phone.startswith(prefix):
            return region
    return None


class CalleService:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    @property
    def enabled(self) -> bool:
        return self.settings.has_calle

    def _client(self) -> Any:
        from calle import CalleClient

        return CalleClient(
            api_key=self.settings.calle_api_key,
            base_url=self.settings.calle_base_url,
        )

    def build_task(
        self,
        business_name: str,
        locale: str,
        *,
        context: str | None = None,
        preferred_language: str | None = None,
    ) -> str:
        """Build the CALL-E task instruction, generated by the LLM in the
        customer's language.

        `preferred_language` (the customer's LLM-detected spoken language,
        `customers.preferred_language`) wins when known; otherwise this falls
        back to `locale` (the order's declared locale — used for a customer's
        very first call, before any language has ever been detected).

        `context` is a pre-sanitized, structured hint produced by the pipeline
        (only verified canonical problem names — never raw transcripts or
        PII); the LLM is asked to weave it into ONE natural follow-up question,
        in the same language as the rest of the script.
        """
        language = preferred_language or locale
        llm = get_llm(self.settings)
        generated = _generate_task_text(llm, business_name, language, context)
        if generated:
            return generated
        # Last-resort, single, language-neutral fallback used ONLY when no LLM
        # provider is configured or the call failed — not a per-language
        # template, just one sentence to keep call dispatch available.
        task = _FALLBACK_TASK.format(business=business_name)
        if context:
            task += "\n\n" + context
        return task

    def webhook_url(self) -> str | None:
        base = self.settings.calle_webhook_base_url.rstrip("/")
        if not base:
            return None
        return f"{base}/api/webhooks/calle"

    def place_call(
        self,
        *,
        phone: str,
        business_name: str,
        locale: str,
        order_id: int,
        correlation_id: str = "",
        business_id: int | None = None,
        environment: str = "dev",
        context: str | None = None,
        preferred_language: str | None = None,
    ) -> dict[str, Any]:
        client = self._client()
        recipient: dict[str, Any] = {
            "phone": phone,
            "locale": _BCP47.get(locale, "en-US"),
        }
        region = region_from_phone(phone)
        if region:
            recipient["region"] = region
        metadata: dict[str, Any] = {
            "order_id": str(order_id),
            "source": "smartfeedback",
            "environment": environment,
        }
        if correlation_id:
            metadata["correlation_id"] = correlation_id
        if business_id is not None:
            metadata["business_id"] = str(business_id)
        try:
            return client.calls.create(
                task=self.build_task(
                    business_name, locale,
                    context=context, preferred_language=preferred_language,
                ),
                recipient=recipient,
                result_schema=RESULT_SCHEMA,
                metadata=metadata,
                webhook_url=self.webhook_url(),
                idempotency_key=f"order-{order_id}",
            )
        finally:
            client.close()

    def fetch_call(self, calle_call_id: str) -> dict[str, Any]:
        client = self._client()
        try:
            return client.calls.get(calle_call_id)
        finally:
            client.close()

    # -- GÖREV 2/3: action-triggered outreach calls -----------------------
    # Fully separate from `build_task`/`place_call` (the core post-delivery
    # feedback call): different purpose, different script, different
    # idempotency key (action-scoped, not order-scoped).

    def build_reengagement_task(
        self, business_name: str, language: str, context: str
    ) -> str | None:
        """LLM-generated re-engagement call script. Returns None (never a
        hardcoded fallback) when no LLM is available or generation fails —
        a personalized outreach message that isn't actually personalized
        defeats its own purpose, so the caller should simply skip it."""
        llm = get_llm(self.settings)
        if llm is None:
            return None
        user = f"Business name: {business_name}\nLanguage: {language}\n"
        if context:
            user += f"Previously reported issue(s) (use verbatim): {context}\n"
        result = complete_json(llm, _REENGAGEMENT_SYSTEM, user)
        if result and result.get("task"):
            text = str(result["task"]).strip()
            return text or None
        return None

    def build_offer_call_task(
        self, business_name: str, language: str, percentage: int
    ) -> str:
        """LLM-generated call script informing a customer of an
        already-human-approved compensation offer. Unlike
        `build_reengagement_task`, this DOES have a single, language-neutral
        fallback sentence: once a human has approved an offer, the customer
        must still be informed even if the LLM is unavailable."""
        llm = get_llm(self.settings)
        user = (
            f"Business name: {business_name}\nLanguage: {language}\n"
            f"Approved percentage: {percentage}\n"
        )
        result = complete_json(llm, _OFFER_SYSTEM.format(percentage=percentage), user) if llm else None
        if result and result.get("task"):
            text = str(result["task"]).strip()
            if text:
                return text
        return _OFFER_FALLBACK_TASK.format(business=business_name, percentage=percentage)

    def place_action_call(
        self,
        *,
        phone: str,
        task: str,
        action_id: int,
        business_id: int | None = None,
        environment: str = "dev",
        preferred_language: str | None = None,
    ) -> dict[str, Any]:
        """Place a CALL-E call driven by a pre-generated task script, keyed
        by an approved/human-reviewed action id (idempotency key
        `action-{action_id}`) instead of an order id. Used exclusively by
        the re-engagement (GÖREV 2) and compensation-offer (GÖREV 3) outreach
        flows — never by the core post-delivery feedback pipeline."""
        client = self._client()
        recipient: dict[str, Any] = {
            "phone": phone,
            "locale": _BCP47.get(preferred_language or "", "en-US"),
        }
        region = region_from_phone(phone)
        if region:
            recipient["region"] = region
        metadata: dict[str, Any] = {
            "action_id": str(action_id),
            "source": "smartfeedback-outreach",
            "environment": environment,
        }
        if business_id is not None:
            metadata["business_id"] = str(business_id)
        try:
            return client.calls.create(
                task=task,
                recipient=recipient,
                result_schema=RESULT_SCHEMA,
                metadata=metadata,
                webhook_url=self.webhook_url(),
                idempotency_key=f"action-{action_id}",
            )
        finally:
            client.close()


def extract_transcript(call: dict[str, Any]) -> str:
    """Extract a readable transcript from a CALL-E call object."""
    parts: list[str] = []
    recipients = call.get("recipients") or []
    for r in recipients:
        attempts = r.get("attempts") or []
        for a in attempts:
            for turn in a.get("transcript_turns") or []:
                speaker = turn.get("speaker", "unknown")
                text = (turn.get("text") or "").strip()
                if text:
                    label = {"user": "Customer", "bot": "Bot"}.get(speaker, "Speaker")
                    parts.append(f"{label}: {text}")
    return "\n".join(parts)


def extract_customer_text(call: dict[str, Any]) -> str:
    """Customer-only text, used as the feedback transcript for analysis."""
    parts: list[str] = []
    recipients = call.get("recipients") or []
    for r in recipients:
        for a in r.get("attempts") or []:
            for turn in a.get("transcript_turns") or []:
                if turn.get("speaker") == "user":
                    text = (turn.get("text") or "").strip()
                    if text:
                        parts.append(text)
    return " ".join(parts)


def recipient_status(call: dict[str, Any]) -> str:
    recipients = call.get("recipients") or []
    if not recipients:
        return "failed"
    return recipients[0].get("status", "failed")


_NO_ANSWER_STATUSES = {"no_answer", "no-answer", "unanswered", "missed"}
_VOICEMAIL_STATUSES = {"voicemail", "voicemail_received", "answering_machine", "left_message"}


def classify_outcome(result: dict[str, Any]) -> str:
    """Normalize a CALL-E result into a terminal outcome taxonomy:

    completed / no_answer / voicemail / failed / canceled / in_progress.

    Distinguishing "no answer" from "failed" matters: a customer who simply did
    not pick up must not be retried, and must not be treated as a transcript
    bearing a real conversation.
    """
    status = (result.get("status") or "").lower()
    if status == "canceled":
        return "canceled"
    if status == "failed":
        return "failed"

    rec = (recipient_status(result) or "").lower()
    if rec in _NO_ANSWER_STATUSES:
        return "no_answer"
    if rec in _VOICEMAIL_STATUSES:
        return "voicemail"

    if status == "completed":
        return "completed"
    if status in ("in_progress", "ringing", "queued", "scheduled", "initiated"):
        return "in_progress"
    return status or "in_progress"
